x <- c(12,45,76,23,6,72,53,54,76,32,56,2,33)
print(mean(x))
print(median(x))
#print(mode(x))
print(Mode(x))
print(range(x))
print(max(x)-min(x))
print(IQR(x))
print(quantile(x))
print(hist(x,xlab = "No. of articles", col = "red",border = "black"))
